#!/bin/bash
# JSON Mapper - TestSprite Test Commands Quick Reference

echo "📋 JSON Mapper - Test Commands"
echo "=================================="
echo ""
echo "✅ Run all tests (one time):"
echo "   npm run test:run"
echo ""
echo "🔄 Run tests in watch mode:"
echo "   npm run test"
echo ""
echo "📊 View test results in UI:"
echo "   npm run test:ui"
echo ""
echo "📈 Generate coverage report:"
echo "   npm run test:coverage"
echo ""
echo "🎯 Run specific test file:"
echo "   npm run test:run -- src/__tests__/JsonPanel.test.jsx"
echo ""
echo "🔍 Run tests matching pattern:"
echo "   npm run test:run -- --grep \"should render\""
echo ""
echo "📝 Update snapshots:"
echo "   npm run test:run -- -u"
echo ""
echo "🚀 Run with verbose output:"
echo "   npm run test:run -- --reporter=verbose"
echo ""
echo "=================================="
echo "Total Tests: 50"
echo "Status: ✅ All Passing"
echo "=================================="
